messages:
  mute-group-message: "<dark_gray><b>[<red>ğŸ™x</red>]</b></dark_gray><white>Jugadores Silenciados</white>"
  unmute-group-message: "<blue><b>[ğŸ™]</b></blue><white>Jugadores con Permiso de Habla</white>"
  mute-player-message: "<red><b>[âœ–]</b></red><white>MicrÃ³fono desactivado, escucha atentamente las instrucciones</white>"
  unmute-player-message: "<green><b>[âœ”]</b></green><white>Ahora tienes permiso de hablar!</white>"
  usage_message: "<red><b>[âœ–]</b></red><white>Uso incorrecto. El target debe ser 'all' o '*'.</white>"
  group-not-found: "<red><b>[âœ–]</b></red><white>El grupo default no existe.</white>"
  reload-message: "<green><b>[âœ”]</b></green><white>Config Reloaded</white>"

    